baseURL: 'https://stawarczyk.pl'
languageCode: pl_PL
title: Grzegorz Stawarczyk - Blog poświęcony zagadnieniom programistycznym
theme: PaperMod
defaultContentLanguage: pl
paginate: 10
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: true
taxonomies:
  category: categories
  tag: tag
minify:
  disableXML: true
  minifyOutput: true
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
params:
  displayFullLangName: false
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Blog stawarczyk.pl
  description: "Blog poświęcony zagadnieniom programistycznym"
  keywords: [ Blog ]
  author: Grzegorz Stawarczyk
  # author: ["Me", "You"] # multiple authors
#  images: [ "<link or path of image for opengraph, twitter-cards>" ]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  analytics:
    google:
      SiteVerificationTag: "kFJxTwwjJ6M960WTCNFl0Vy8dqYHTSTr2tME8-nMFSs"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.png"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"

  label:
    text: "Blog stawarczyk.pl"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tag

  # home-info mode
  homeInfoParams:
    Title: "Grzegorz Stawarczyk"
    Content: "Blog poświęcony zagadnieniom programistycznym"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/gstawarczyk"
    - name: linkedin
      url: "https://www.linkedin.com/in/gstawarczyk/"
    - name: github
      url: "https://github.com/g-stawarczyk/"
    - name: instagram
      url: "https://www.instagram.com/gstawarczyk/"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

#  editPost:
#    URL: "https://github.com/<path_to_repo>/content"
#    Text: "Suggest Changes" # edit text
#    appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    lineNos: true
    style: monokai
  goldmark:
    renderer:
      unsafe: false
      xhtml: true
permalinks:
  posts: /:year/:month/:slug/
languages:
  pl:
    contentDir: content/polish
    languageName: Polish
    weight: 1
    menu:
      main:
        - name: Szukaj
          url: szukaj
          weight: 3
        - name: Kategorie
          url: categories
          weight: 1
        - name: Tagi
          url: tag
          weight: 2
#  en:
#    contentDir: content/english
#    languageName: English
#    weight: 10
#    menu:
#      main:
#        - name: Search
#          url: search
#          weight: 1
#        - name: Categories
#          url: categories
#          weight: 1
#        - name: Tags
#          url: tag
#          weight: 2
